import streamlit as st
import requests
import hashlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime
from fpdf import FPDF

# --- 1. PAGE CONFIGURATION ---
st.set_page_config(
    page_title="CyberSentinel Pro",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 2. CUSTOM CSS (Visual Styling) ---
st.markdown("""
<style>
    /* Background Gradient */
    .stApp {
        background: linear-gradient(135deg, #74ebd5 0%, #ACB6E5 100%);
        background-attachment: fixed;
    }
    h1 {
        color: #2c3e50;
        text-align: center;
        font-family: 'Helvetica', sans-serif;
        font-weight: 800;
        text-shadow: 2px 2px 4px rgba(0,0,0,0.1);
    }
    div[data-testid="stMetric"] {
        background-color: rgba(255, 255, 255, 0.6);
        border-radius: 15px;
        padding: 20px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        backdrop-filter: blur(10px);
    }
    .stButton>button {
        width: 100%;
        border-radius: 50px;
        height: 3em;
        background: linear-gradient(90deg, #FF4B4B 0%, #FF9068 100%);
        color: white;
        font-weight: bold;
        border: none;
        box-shadow: 0 4px 15px rgba(255, 75, 75, 0.4);
    }
</style>
""", unsafe_allow_html=True)

# --- 3. CREATIVE PDF GENERATOR (The New Feature) ---
class CreativePDF(FPDF):
    def header(self):
        # Draw a Dark Blue Banner at the top
        self.set_fill_color(44, 62, 80)  # Dark Blue
        self.rect(0, 0, 210, 40, 'F')    # Rectangle covering top
        
        # Add Title Text
        self.set_font('Arial', 'B', 24)
        self.set_text_color(255, 255, 255) # White text
        self.cell(0, 20, 'CyberSentinel', 0, 1, 'C')
        
        self.set_font('Arial', '', 12)
        self.cell(0, 5, 'OFFICIAL SECURITY AUDIT REPORT', 0, 1, 'C')
        self.ln(20) # Add spacing after header

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by CyberSentinel System', 0, 0, 'C')

def generate_creative_pdf(email, score, breaches):
    pdf = CreativePDF()
    pdf.add_page()
    
    # SECTION 1: TARGET INFO
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, f"AUDIT TARGET: {email}", 0, 1, 'L')
    pdf.cell(0, 10, f"GENERATED ON: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'L')
    pdf.line(10, 65, 200, 65) # Draw a separator line
    
    # SECTION 2: RISK SCORE CARD
    pdf.ln(10)
    # Draw a colored box for the score
    pdf.set_fill_color(240, 240, 240) # Light Grey background
    pdf.rect(10, 75, 190, 40, 'F') 
    
    pdf.set_y(80)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "IDENTITY RISK SCORE", 0, 1, 'C')
    
    pdf.set_font("Arial", 'B', 30)
    if score > 50:
        pdf.set_text_color(192, 57, 43) # Red for danger
        status = "CRITICAL RISK"
    else:
        pdf.set_text_color(39, 174, 96) # Green for safe
        status = "SECURE"
        
    pdf.cell(0, 15, f"{score}/100 ({status})", 0, 1, 'C')
    pdf.set_text_color(0, 0, 0) # Reset color

    # SECTION 3: BREACH TABLE
    pdf.ln(20)
    pdf.set_font("Arial", 'B', 14)
    # Table Header with Blue Background
    pdf.set_fill_color(44, 62, 80)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, " FORENSIC EVIDENCE LOG", 1, 1, 'L', fill=True)
    
    # Table Rows
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", '', 10)
    
    fill = False # For Zebra striping
    if breaches:
        for b in breaches:
            # Alternate row colors
            if fill:
                pdf.set_fill_color(230, 230, 230) # Light Grey
            else:
                pdf.set_fill_color(255, 255, 255) # White
                
            # Clean up text to prevent PDF errors
            name = str(b['Name'])
            date = str(b.get('BreachDate', 'N/A'))
            desc = str(b.get('Description', 'No details'))[:70] + "..." # Truncate long text
            
            # Draw row
            pdf.cell(40, 10, f" {name}", 1, 0, 'L', fill=fill)
            pdf.cell(30, 10, f" {date}", 1, 0, 'L', fill=fill)
            pdf.cell(0, 10, f" {desc}", 1, 1, 'L', fill=fill)
            
            fill = not fill # Toggle color for next row
    else:
        pdf.cell(0, 10, " No breaches found.", 1, 1, 'L')

    pdf.output("Risk_Report.pdf")

# --- 4. BACKEND LOGIC (Same as before) ---
def get_mock_breaches():
    return [
        {"Name": "LinkedIn", "BreachDate": "2016-05-17", "DataClasses": ["Email", "Passwords", "Job titles"], "Description": "164 Million accounts exposed in massive professional network hack."},
        {"Name": "Adobe", "BreachDate": "2013-10-04", "DataClasses": ["Email", "Hints", "Usernames"], "Description": "153 Million accounts exposed affecting Creative Cloud users."},
        {"Name": "Zomato", "BreachDate": "2017-05-18", "DataClasses": ["Email", "Passwords"], "Description": "17 Million user records leaked from food delivery giant."},
        {"Name": "Canva", "BreachDate": "2019-05-24", "DataClasses": ["Email", "Names", "Locations"], "Description": "Graphic design platform database compromised."}
    ]

def get_real_breaches(email):
    url = f"https://leakcheck.io/api/public?check={email}"
    try:
        response = requests.get(url, timeout=5)
        data = response.json()
        if data.get('success') and data.get('sources'):
            real_breaches = []
            for source in data.get('sources'):
                name = source.get('name') if isinstance(source, dict) else source
                real_breaches.append({
                    "Name": name, "BreachDate": "2021-01-01", 
                    "DataClasses": ["Email", "Password"], "Description": "Public Database Leak"
                })
            return real_breaches
        return []
    except:
        return None

def check_password_pwned(password):
    sha1pass = hashlib.sha1(password.encode('utf-8')).hexdigest().upper()
    prefix, suffix = sha1pass[:5], sha1pass[5:]
    try:
        res = requests.get(f"https://api.pwnedpasswords.com/range/{prefix}", timeout=5)
        if res.status_code == 200:
            for line in res.text.splitlines():
                h, count = line.split(':')
                if h == suffix: return int(count)
    except: return -1
    return 0

def calculate_risk(breaches):
    score = 0
    weights = {'Passwords': 30, 'Email': 10, 'Phone': 50}
    for b in breaches:
        for dtype in b.get('DataClasses', []):
            score += weights.get(dtype, 15)
    return min(score, 100)

# --- 5. THE UI LAYOUT ---
st.markdown("<h1>🛡️ CyberSentinel <br><span style='font-size: 20px; color: #555;'>Advanced Identity Leak Auditor</span></h1>", unsafe_allow_html=True)
st.divider()

with st.sidebar:
    st.markdown("### ⚙️ Control Panel")
    email_input = st.text_input("Target Email Address", "demo@test.com")
    pass_input = st.text_input("Password Check (Optional)", type="password")
    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("🚀 INITIATE SCAN"):
        st.session_state['run'] = True
    st.markdown("---")
    st.caption("🔒 Zero-Knowledge Architecture.")

if st.session_state.get('run'):
    with st.spinner("🕵️ Scouring Dark Web Databases..."):
        breaches = get_real_breaches(email_input)
        is_sim = False
        if not breaches and email_input == "demo@test.com":
            breaches = get_mock_breaches()
            is_sim = True
        risk_score = calculate_risk(breaches) if breaches else 0

    if risk_score > 50:
        st.error(f"🚨 CRITICAL THREAT DETECTED: Risk Score {risk_score}/100")
    elif risk_score > 0:
        st.warning(f"⚠️ MODERATE RISK: Risk Score {risk_score}/100")
    else:
        st.success("✅ SYSTEM SECURE: No data breaches found.")

    if is_sim: st.caption("ℹ️ Running in Simulation Mode for Demonstration")

    tab1, tab2, tab3 = st.tabs(["📊 Live Dashboard", "🕸️ Attack Map", "🔑 Password Lab"])

    with tab1:
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Breaches", len(breaches) if breaches else 0)
        col2.metric("Identity Risk Score", f"{risk_score}/100", delta="High Risk" if risk_score > 50 else "Safe")
        col3.metric("Data Source", "Simulation" if is_sim else "Live API")

        st.markdown("### 📜 Forensic Log")
        if breaches:
            for b in breaches:
                with st.expander(f"🔴 {b['Name']} ({b.get('BreachDate', 'N/A')})"):
                    st.write(f"**Description:** {b.get('Description', 'No details available.')}")
                    st.write(f"**Compromised Data:** {', '.join(b.get('DataClasses', []))}")
        else: st.info("No breaches to display.")

    with tab2:
        st.markdown("### 📅 Timeline of Compromise")
        if breaches:
            dates = [datetime.strptime(b.get('BreachDate', '2021-01-01'), "%Y-%m-%d") for b in breaches]
            names = [b['Name'] for b in breaches]
            fig, ax = plt.subplots(figsize=(10, 4))
            fig.patch.set_alpha(0)
            ax.patch.set_alpha(0)
            markerline, stemline, baseline = ax.stem(dates, [1]*len(dates))
            plt.setp(markerline, marker='D', markersize=8, markeredgecolor="#FF4B4B", markerfacecolor="white")
            plt.setp(stemline, color='#2c3e50', linestyle='--')
            ax.get_yaxis().set_visible(False)
            ax.spines['top'].set_visible(False)
            ax.spines['right'].set_visible(False)
            ax.spines['left'].set_visible(False)
            ax.spines['bottom'].set_color('#2c3e50')
            ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
            for d, name in zip(dates, names):
                ax.annotate(name, xy=(d, 1.1), xytext=(0, 5), textcoords="offset points", ha='center', fontweight='bold', color="#2c3e50")
            st.pyplot(fig)
        else: st.info("No timeline data available.")

    with tab3:
        st.markdown("### 🔐 Password Strength Analysis")
        if pass_input:
            leaks = check_password_pwned(pass_input)
            if leaks > 0: st.error(f"Password exposed {leaks:,} times. CHANGE IMMEDIATELY.")
            elif leaks == 0: st.success("Password NOT found in known leaks.")
            else: st.warning("Connection failed.")
        else: st.info("Enter password in sidebar to test.")

    st.divider()
    if st.button("📄 Export Forensic PDF Report"):
        # CALLING THE NEW CREATIVE PDF FUNCTION
        generate_creative_pdf(email_input, risk_score, breaches if breaches else [])
        with open("Risk_Report.pdf", "rb") as f:
            st.download_button("📥 Download PDF", f, "Risk_Report.pdf")
else:
    st.info("👈 Enter an email in the sidebar and click 'INITIATE SCAN' to begin.")
