import streamlit as st
import requests
import hashlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime
from fpdf import FPDF

# --- 1. PAGE CONFIGURATION ---
st.set_page_config(
    page_title="CyberSentinel Pro",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 2. CUSTOM CSS (HEADER VISIBILITY FIX) ---
st.markdown("""
<style>
    /* 1. BACKGROUND */
    .stApp {
        background: linear-gradient(135deg, #00C9FF 0%, #92FE9D 100%);
        background-attachment: fixed;
    }
    
    /* 2. *** FIXED HEADER VISIBILITY *** */
    /* This puts a white glass bar behind the top menu buttons so you can see them */
    header[data-testid="stHeader"] {
        background-color: rgba(255, 255, 255, 0.8) !important;
        backdrop-filter: blur(10px);
        border-bottom: 1px solid rgba(255,255,255,0.5);
    }
    /* Force the text color of the top menu to be black */
    header[data-testid="stHeader"] * {
        color: #000000 !important;
    }

    /* 3. TEXT VISIBILITY (Force Dark Text) */
    h1, h2, h3, h4, p, li, span, div, label {
        color: #0f172a !important;
        text-shadow: none !important;
    }
    
    /* 4. BUTTON FIX */
    .stButton > button {
        background-color: #0f172a !important; /* Dark Navy Background */
        color: #ffffff !important;             /* Force WHITE Text */
        border: 1px solid white !important;
        border-radius: 8px;
        font-weight: bold;
    }
    .stButton > button p { color: #ffffff !important; }

    .stButton > button:hover {
        background-color: #1e293b !important;
        transform: scale(1.02);
    }

    /* 5. SIDEBAR */
    [data-testid="stSidebar"] {
        background-color: rgba(255, 255, 255, 0.9) !important;
        border-right: 1px solid rgba(255,255,255,0.5);
        backdrop-filter: blur(10px);
    }

    /* 6. CARDS */
    div[data-testid="stMetric"], .stTabs [data-baseweb="tab-panel"] {
        background-color: rgba(255, 255, 255, 0.75);
        border-radius: 15px;
        padding: 20px;
        border: 1px solid #ffffff;
        box-shadow: 0 4px 15px rgba(0,0,0,0.05);
        backdrop-filter: blur(10px);
    }
    
    /* 7. INPUT BOXES */
    input[type="text"], input[type="password"] {
        color: #000000 !important;
        background-color: #ffffff !important;
        border: 1px solid #ccc;
    }

    /* 8. TABS */
    .stTabs [data-baseweb="tab"] {
        background-color: rgba(255,255,255,0.5);
        border-radius: 5px;
        color: #0f172a !important;
        font-weight: bold;
    }
    .stTabs [aria-selected="true"] {
        background-color: #ffffff;
        box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    }
</style>
""", unsafe_allow_html=True)

# --- 3. CREATIVE PDF GENERATOR ---
class CreativePDF(FPDF):
    def header(self):
        self.set_fill_color(15, 23, 42) # Dark Navy Header
        self.rect(0, 0, 210, 40, 'F')
        self.set_font('Arial', 'B', 24)
        self.set_text_color(255, 255, 255)
        self.cell(0, 20, 'CyberSentinel', 0, 1, 'C')
        self.set_font('Arial', '', 12)
        self.cell(0, 5, 'OFFICIAL SECURITY AUDIT REPORT', 0, 1, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by CyberSentinel System', 0, 0, 'C')

def generate_creative_pdf(email, score, breaches):
    pdf = CreativePDF()
    pdf.add_page()
    
    # Target Info
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, f"AUDIT TARGET: {email}", 0, 1, 'L')
    pdf.cell(0, 10, f"DATE: {datetime.now().strftime('%Y-%m-%d')}", 0, 1, 'L')
    pdf.line(10, 65, 200, 65)
    
    # Score Box
    pdf.ln(10)
    pdf.set_fill_color(240, 240, 250)
    pdf.rect(10, 75, 190, 40, 'F') 
    pdf.set_y(80)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "IDENTITY RISK SCORE", 0, 1, 'C')
    pdf.set_font("Arial", 'B', 30)
    if score > 50:
        pdf.set_text_color(220, 20, 60)
        status = "CRITICAL RISK"
    else:
        pdf.set_text_color(0, 128, 0)
        status = "SECURE"
    pdf.cell(0, 15, f"{score}/100 ({status})", 0, 1, 'C')
    pdf.set_text_color(0, 0, 0)

    # Table
    pdf.ln(20)
    pdf.set_font("Arial", 'B', 14)
    pdf.set_fill_color(15, 23, 42)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, " FORENSIC EVIDENCE LOG", 1, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", '', 10)
    
    fill = False
    if breaches:
        for b in breaches:
            if fill: pdf.set_fill_color(230, 240, 255)
            else: pdf.set_fill_color(255, 255, 255)
            
            name = str(b['Name'])
            date = str(b.get('BreachDate', 'N/A'))
            desc = str(b.get('Description', 'No details'))[:70] + "..."
            
            pdf.cell(40, 10, f" {name}", 1, 0, 'L', fill=fill)
            pdf.cell(30, 10, f" {date}", 1, 0, 'L', fill=fill)
            pdf.cell(0, 10, f" {desc}", 1, 1, 'L', fill=fill)
            fill = not fill
    else:
        pdf.cell(0, 10, " No breaches found.", 1, 1, 'L')

    pdf.output("Risk_Report.pdf")

# --- 4. BACKEND LOGIC ---
def get_mock_breaches():
    return [
        {"Name": "LinkedIn", "BreachDate": "2016-05-17", "DataClasses": ["Email", "Passwords", "Job titles"], "Description": "164 Million accounts exposed in massive professional network hack."},
        {"Name": "Adobe", "BreachDate": "2013-10-04", "DataClasses": ["Email", "Hints", "Usernames"], "Description": "153 Million accounts exposed affecting Creative Cloud users."},
        {"Name": "Zomato", "BreachDate": "2017-05-18", "DataClasses": ["Email", "Passwords"], "Description": "17 Million user records leaked from food delivery giant."},
        {"Name": "Canva", "BreachDate": "2019-05-24", "DataClasses": ["Email", "Names", "Locations"], "Description": "Graphic design platform database compromised."}
    ]

def get_real_breaches(email):
    url = f"https://leakcheck.io/api/public?check={email}"
    try:
        response = requests.get(url, timeout=5)
        data = response.json()
        if data.get('success') and data.get('sources'):
            real_breaches = []
            for source in data.get('sources'):
                name = source.get('name') if isinstance(source, dict) else source
                real_breaches.append({
                    "Name": name, "BreachDate": "2021-01-01", 
                    "DataClasses": ["Email", "Password"], "Description": "Public Database Leak"
                })
            return real_breaches
        return []
    except:
        return None

def check_password_pwned(password):
    sha1pass = hashlib.sha1(password.encode('utf-8')).hexdigest().upper()
    prefix, suffix = sha1pass[:5], sha1pass[5:]
    try:
        res = requests.get(f"https://api.pwnedpasswords.com/range/{prefix}", timeout=5)
        if res.status_code == 200:
            for line in res.text.splitlines():
                h, count = line.split(':')
                if h == suffix: return int(count)
    except: return -1
    return 0

def calculate_risk(breaches):
    score = 0
    weights = {'Passwords': 30, 'Email': 10, 'Phone': 50}
    for b in breaches:
        for dtype in b.get('DataClasses', []):
            score += weights.get(dtype, 15)
    return min(score, 100)

# --- 5. THE UI LAYOUT ---
st.markdown("<h1>🛡️ CyberSentinel <br><span style='font-size: 20px;'>Advanced Identity Leak Auditor</span></h1>", unsafe_allow_html=True)
st.divider()

with st.sidebar:
    st.markdown("### ⚙️ Control Panel")
    email_input = st.text_input("Target Email Address", "demo@test.com")
    pass_input = st.text_input("Password Check (Optional)", type="password")
    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("🚀 INITIATE SCAN"):
        st.session_state['run'] = True
    st.markdown("---")
    st.caption("🔒 Zero-Knowledge Architecture.")

if st.session_state.get('run'):
    with st.spinner("🕵️ Scouring Dark Web Databases..."):
        breaches = get_real_breaches(email_input)
        is_sim = False
        if not breaches and email_input == "demo@test.com":
            breaches = get_mock_breaches()
            is_sim = True
        risk_score = calculate_risk(breaches) if breaches else 0

    if risk_score > 50:
        st.error(f"🚨 CRITICAL THREAT DETECTED: Risk Score {risk_score}/100")
    elif risk_score > 0:
        st.warning(f"⚠️ MODERATE RISK: Risk Score {risk_score}/100")
    else:
        st.success("✅ SYSTEM SECURE: No data breaches found.")

    if is_sim: st.caption("ℹ️ Running in Simulation Mode for Demonstration")

    tab1, tab2, tab3 = st.tabs(["📊 Live Dashboard", "🕸️ Attack Map", "🔑 Password Lab"])

    with tab1:
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Breaches", len(breaches) if breaches else 0)
        col2.metric("Identity Risk Score", f"{risk_score}/100", delta="High Risk" if risk_score > 50 else "Safe")
        col3.metric("Data Source", "Simulation" if is_sim else "Live API")

        st.markdown("### 📜 Forensic Log")
        if breaches:
            for b in breaches:
                with st.expander(f"🔴 {b['Name']} ({b.get('BreachDate', 'N/A')})"):
                    st.write(f"**Description:** {b.get('Description', 'No details available.')}")
                    st.write(f"**Compromised Data:** {', '.join(b.get('DataClasses', []))}")
        else: st.info("No breaches to display.")

    with tab2:
        st.markdown("### 📅 Timeline of Compromise")
        if breaches:
            dates = [datetime.strptime(b.get('BreachDate', '2021-01-01'), "%Y-%m-%d") for b in breaches]
            names = [b['Name'] for b in breaches]
            fig, ax = plt.subplots(figsize=(10, 4))
            fig.patch.set_alpha(0)
            ax.patch.set_alpha(0)
            # Dark Blue Chart
            markerline, stemline, baseline = ax.stem(dates, [1]*len(dates))
            plt.setp(markerline, marker='D', markersize=8, markeredgecolor="#0f172a", markerfacecolor="white")
            plt.setp(stemline, color='#0f172a', linestyle='--')
            ax.get_yaxis().set_visible(False)
            ax.spines['top'].set_visible(False)
            ax.spines['right'].set_visible(False)
            ax.spines['left'].set_visible(False)
            ax.spines['bottom'].set_color('#0f172a')
            ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
            # X Labels Black
            ax.tick_params(axis='x', colors='#000')
            for d, name in zip(dates, names):
                ax.annotate(name, xy=(d, 1.1), xytext=(0, 5), textcoords="offset points", ha='center', fontweight='bold', color="#0f172a")
            st.pyplot(fig)
        else: st.info("No timeline data available.")

    with tab3:
        st.markdown("### 🔐 Password Strength Analysis")
        if pass_input:
            leaks = check_password_pwned(pass_input)
            if leaks > 0: st.error(f"Password exposed {leaks:,} times. CHANGE IMMEDIATELY.")
            elif leaks == 0: st.success("Password NOT found in known leaks.")
            else: st.warning("Connection failed.")
        else: st.info("Enter password in sidebar to test.")

    st.divider()
    if st.button("📄 Export Forensic PDF Report"):
        generate_creative_pdf(email_input, risk_score, breaches if breaches else [])
        with open("Risk_Report.pdf", "rb") as f:
            st.download_button("📥 Download PDF", f, "Risk_Report.pdf")
else:
    st.info("👈 Enter an email in the sidebar and click 'INITIATE SCAN' to begin.")
